### ISSUE TITLE
Variable prefix for functions

### ISSUE THREAD

**Issue by ChaosPaladin** [madyanov/nasc-decompiler#25]
Will be cool make config for enable add prefix for functions, like:

`Whisper(creature, "** Direction : " + GetDirectionToTarget(creature) * 182 + "  ");` ->
`myself.Whisper(creature, "** Direction : " + (myself.GetDirectionToTarget(creature) * 182) + "  ");`

`if (Rand(10000) < Dispel_Debuff_Prob)` ->
`if (gg.Rand(10000) < Dispel_Debuff_Prob)`

`AddEventCampaignPoint(speller, 1, 1, 2, 102, 5);` ->
`gg.AddEventCampaignPoint(attacker, 1, 1, 2, 102, 5);`

`SetAsNull(myself.c_ai1);` ->
`gg.SetAsNull(myself.c_ai1);`

**Comment by madyanov** [comment]
Why is this needed? As far as I know, compiler understands function calls without `gg` and `myself` objects.
BTW: object removing can be disabled here https://github.com/madyanov/nasc-decompiler/blob/c522a7722ee8efddf55a76c8a9d7a7346289e044/core/generators/nasc.php#L186
