### ISSUE TITLE
Advext H5

### ISSUE THREAD

**Issue by Boffice** [madyanov/nasc-decompiler#29]
I get this on advext H5:

Decompile ai_a_seed_elite_monsterPHP Fatal error:  Uncaught RuntimeException: Function 268632201 not found in C:\Users\samar\Downloads\nasc-decompiler-master\core\data.php:67
Stack trace:
#0 C:\Users\samar\Downloads\nasc-decompiler-master\core\parser.php(443): Data->getFunction(268632201)
#1 C:\Users\samar\Downloads\nasc-decompiler-master\core\parser.php(117): Parser->parseFuncCall(Object(Token))
#2 C:\Users\samar\Downloads\nasc-decompiler-master\core\main.php(271): Parser->parseClass(Object(Token))
#3 C:\Users\samar\Downloads\nasc-decompiler-master\core\main.php(75): Main->decompile()
#4 C:\Users\samar\Downloads\nasc-decompiler-master\core\main.php(392): Main->run()
#5 {main}
  thrown in C:\Users\samar\Downloads\nasc-decompiler-master\core\data.php on line 67

**Comment by madyanov** [comment]
Yeah, you need to add this function (268632201) to `data/h5/functions.json`.

**Comment by Boffice** [comment]
It runs Advext H5 as GF i suppose because it is extended from GF. shell i force run it through h5 or i jsut add function to gf ?

**Comment by madyanov** [comment]
For h5 you should use h5.
